# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setinfowin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_infoWin(object):
    def setupUi(self, infoWin):
        infoWin.setObjectName("infoWin")
        infoWin.setWindowModality(QtCore.Qt.NonModal)
        infoWin.resize(831, 612)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 208, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 208, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 208, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 208, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        infoWin.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoWin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(infoWin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 571))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tbv = QtWidgets.QTableView(self.gridLayoutWidget)
        self.tbv.setObjectName("tbv")
        self.gridLayout.addWidget(self.tbv, 0, 0, 1, 1)
        infoWin.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(infoWin)
        self.toolBar.setMouseTracking(False)
        self.toolBar.setTabletTracking(False)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setIconSize(QtCore.QSize(40, 90))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        infoWin.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.tool_a = QtWidgets.QAction(infoWin)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ico/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("ico/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tool_a.setIcon(icon1)
        self.tool_a.setObjectName("tool_a")
        self.tool_d = QtWidgets.QAction(infoWin)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/del1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("ico/remove-ticket.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tool_d.setIcon(icon2)
        self.tool_d.setObjectName("tool_d")
        self.tool_s = QtWidgets.QAction(infoWin)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ico/28-缴费结果-蓝.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_s.setIcon(icon3)
        self.tool_s.setObjectName("tool_s")
        self.tool_c = QtWidgets.QAction(infoWin)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ico/ico退出系统.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_c.setIcon(icon4)
        self.tool_c.setObjectName("tool_c")
        self.toolBar.addAction(self.tool_a)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tool_d)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tool_s)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tool_c)

        self.retranslateUi(infoWin)
        QtCore.QMetaObject.connectSlotsByName(infoWin)

    def retranslateUi(self, infoWin):
        _translate = QtCore.QCoreApplication.translate
        infoWin.setWindowTitle(_translate("infoWin", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("infoWin", "toolBar"))
        self.tool_a.setText(_translate("infoWin", "添加"))
        self.tool_a.setToolTip(_translate("infoWin", "添加数据"))
        self.tool_d.setText(_translate("infoWin", "删除"))
        self.tool_d.setToolTip(_translate("infoWin", "删除数据"))
        self.tool_s.setText(_translate("infoWin", "保存"))
        self.tool_s.setToolTip(_translate("infoWin", "保存修改"))
        self.tool_c.setText(_translate("infoWin", "退出"))
        self.tool_c.setToolTip(_translate("infoWin", "退出窗口"))

