# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workwin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 592)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/rent-a-car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pan_box = QtWidgets.QGroupBox(Form)
        self.pan_box.setGeometry(QtCore.QRect(50, 12, 757, 581))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pan_box.setFont(font)
        self.pan_box.setTitle("")
        self.pan_box.setCheckable(False)
        self.pan_box.setObjectName("pan_box")
        self.btn_save = QtWidgets.QPushButton(self.pan_box)
        self.btn_save.setGeometry(QtCore.QRect(296, 538, 160, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ico/28-缴费结果-蓝.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon1)
        self.btn_save.setIconSize(QtCore.QSize(21, 21))
        self.btn_save.setObjectName("btn_save")
        self.btn_close = QtWidgets.QPushButton(self.pan_box)
        self.btn_close.setGeometry(QtCore.QRect(540, 538, 160, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_close.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/delete1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setIconSize(QtCore.QSize(20, 22))
        self.btn_close.setObjectName("btn_close")
        self.groupBox_2 = QtWidgets.QGroupBox(self.pan_box)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 12, 725, 82))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_serch = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_serch.setGeometry(QtCore.QRect(370, 34, 144, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_serch.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ico/已申请的缴费证明.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_serch.setIcon(icon3)
        self.btn_serch.setIconSize(QtCore.QSize(25, 25))
        self.btn_serch.setObjectName("btn_serch")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 99, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txt_serch = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_serch.setGeometry(QtCore.QRect(110, 38, 222, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_serch.setFont(font)
        self.txt_serch.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_serch.setObjectName("txt_serch")
        self.btn_del = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_del.setEnabled(False)
        self.btn_del.setGeometry(QtCore.QRect(564, 34, 144, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_del.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ico/del1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del.setIcon(icon4)
        self.btn_del.setIconSize(QtCore.QSize(25, 25))
        self.btn_del.setObjectName("btn_del")
        self.groupBox_3 = QtWidgets.QGroupBox(self.pan_box)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 112, 733, 414))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(4, 14, 699, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.txt_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.txt_name.setFont(font)
        self.txt_name.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_name.setObjectName("txt_name")
        self.gridLayout.addWidget(self.txt_name, 1, 2, 1, 1)
        self.comb_zd = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comb_zd.setFont(font)
        self.comb_zd.setObjectName("comb_zd")
        self.gridLayout.addWidget(self.comb_zd, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 2)
        self.txt_lb = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.txt_lb.setFont(font)
        self.txt_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_lb.setObjectName("txt_lb")
        self.gridLayout.addWidget(self.txt_lb, 1, 6, 1, 1)
        self.txt_mc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.txt_mc.setFont(font)
        self.txt_mc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_mc.setText("")
        self.txt_mc.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_mc.setDragEnabled(False)
        self.txt_mc.setReadOnly(False)
        self.txt_mc.setObjectName("txt_mc")
        self.gridLayout.addWidget(self.txt_mc, 0, 6, 1, 1)
        self.txt_pz = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_pz.setFont(font)
        self.txt_pz.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_pz.setObjectName("txt_pz")
        self.gridLayout.addWidget(self.txt_pz, 2, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 5, 1, 1)
        self.txt_xh = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.txt_xh.setFont(font)
        self.txt_xh.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_xh.setObjectName("txt_xh")
        self.gridLayout.addWidget(self.txt_xh, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 5, 1, 1)
        self.txt_dw = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.txt_dw.setFont(font)
        self.txt_dw.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_dw.setObjectName("txt_dw")
        self.gridLayout.addWidget(self.txt_dw, 4, 2, 1, 1)
        self.txt_je = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_je.setFont(font)
        self.txt_je.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_je.setObjectName("txt_je")
        self.gridLayout.addWidget(self.txt_je, 5, 2, 1, 1)
        self.txt_cs = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_cs.setFont(font)
        self.txt_cs.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cs.setObjectName("txt_cs")
        self.gridLayout.addWidget(self.txt_cs, 5, 6, 1, 1)
        self.txt_bz = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_bz.setFont(font)
        self.txt_bz.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_bz.setObjectName("txt_bz")
        self.gridLayout.addWidget(self.txt_bz, 4, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 5, 1, 1)
        self.txt_gcpz = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_gcpz.setFont(font)
        self.txt_gcpz.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_gcpz.setPlaceholderText("")
        self.txt_gcpz.setObjectName("txt_gcpz")
        self.gridLayout.addWidget(self.txt_gcpz, 6, 2, 1, 1)
        self.txt_gcdw = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.txt_gcdw.setFont(font)
        self.txt_gcdw.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_gcdw.setPlaceholderText("")
        self.txt_gcdw.setObjectName("txt_gcdw")
        self.gridLayout.addWidget(self.txt_gcdw, 6, 6, 1, 1)
        self.txt_id = QtWidgets.QLineEdit(self.pan_box)
        self.txt_id.setEnabled(True)
        self.txt_id.setGeometry(QtCore.QRect(300, 540, 139, 20))
        self.txt_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_id.setObjectName("txt_id")
        self.txt_worker = QtWidgets.QLineEdit(self.pan_box)
        self.txt_worker.setGeometry(QtCore.QRect(550, 540, 113, 20))
        self.txt_worker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_worker.setObjectName("txt_worker")
        self.txt_time = QtWidgets.QLineEdit(self.pan_box)
        self.txt_time.setGeometry(QtCore.QRect(550, 540, 113, 20))
        self.txt_time.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_time.setObjectName("txt_time")
        self.btn_clear = QtWidgets.QPushButton(self.pan_box)
        self.btn_clear.setGeometry(QtCore.QRect(60, 538, 156, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ico/application.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clear.setIcon(icon5)
        self.btn_clear.setIconSize(QtCore.QSize(20, 20))
        self.btn_clear.setObjectName("btn_clear")
        self.txt_time.raise_()
        self.txt_worker.raise_()
        self.txt_id.raise_()
        self.btn_save.raise_()
        self.btn_close.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.btn_clear.raise_()
        self.dict_pan = QtWidgets.QTableView(Form)
        self.dict_pan.setGeometry(QtCore.QRect(802, 360, 261, 165))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dict_pan.setFont(font)
        self.dict_pan.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.dict_pan.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.dict_pan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dict_pan.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.dict_pan.setGridStyle(QtCore.Qt.DashDotLine)
        self.dict_pan.setObjectName("dict_pan")

        self.retranslateUi(Form)
        self.txt_dw.returnPressed.connect(self.txt_je.setFocus)
        self.txt_je.returnPressed.connect(self.txt_gcpz.setFocus)
        self.txt_gcpz.returnPressed.connect(self.txt_gcdw.setFocus)
        self.txt_gcdw.returnPressed.connect(self.btn_save.setFocus)
        self.txt_bz.returnPressed.connect(self.txt_je.setFocus)
        self.btn_close.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.txt_serch, self.txt_mc)
        Form.setTabOrder(self.txt_mc, self.txt_name)
        Form.setTabOrder(self.txt_name, self.txt_lb)
        Form.setTabOrder(self.txt_lb, self.txt_xh)
        Form.setTabOrder(self.txt_xh, self.txt_pz)
        Form.setTabOrder(self.txt_pz, self.txt_dw)
        Form.setTabOrder(self.txt_dw, self.txt_je)
        Form.setTabOrder(self.txt_je, self.txt_gcpz)
        Form.setTabOrder(self.txt_gcpz, self.txt_gcdw)
        Form.setTabOrder(self.txt_gcdw, self.btn_save)
        Form.setTabOrder(self.btn_save, self.txt_bz)
        Form.setTabOrder(self.txt_bz, self.txt_cs)
        Form.setTabOrder(self.txt_cs, self.btn_serch)
        Form.setTabOrder(self.btn_serch, self.btn_del)
        Form.setTabOrder(self.btn_del, self.comb_zd)
        Form.setTabOrder(self.comb_zd, self.btn_close)
        Form.setTabOrder(self.btn_close, self.dict_pan)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "办理业务"))
        self.btn_save.setText(_translate("Form", "缴  费"))
        self.btn_close.setText(_translate("Form", "退  出"))
        self.groupBox_2.setTitle(_translate("Form", "查询"))
        self.btn_serch.setText(_translate("Form", "保存修改"))
        self.label.setText(_translate("Form", "查找车牌："))
        self.txt_serch.setPlaceholderText(_translate("Form", "输入车牌号"))
        self.btn_del.setText(_translate("Form", "删除数据"))
        self.groupBox_3.setTitle(_translate("Form", "办理业务"))
        self.label_6.setText(_translate("Form", "车辆型号："))
        self.label_2.setText(_translate("Form", "收费站点："))
        self.label_3.setText(_translate("Form", "单位名称："))
        self.txt_name.setPlaceholderText(_translate("Form", "(必填)"))
        self.txt_lb.setPlaceholderText(_translate("Form", "(必填)"))
        self.txt_pz.setPlaceholderText(_translate("Form", "(必填)"))
        self.label_7.setText(_translate("Form", "车牌照号："))
        self.label_5.setText(_translate("Form", "车主姓名："))
        self.label_4.setText(_translate("Form", "车辆类别："))
        self.label_9.setText(_translate("Form", "吨位/座位："))
        self.label_12.setText(_translate("Form", "缴费标准："))
        self.label_14.setText(_translate("Form", "通行次数："))
        self.txt_je.setPlaceholderText(_translate("Form", "(必填)"))
        self.txt_cs.setPlaceholderText(_translate("Form", "自动"))
        self.txt_bz.setPlaceholderText(_translate("Form", "自动"))
        self.label_13.setText(_translate("Form", "缴费金额："))
        self.label_10.setText(_translate("Form", "挂车车牌："))
        self.label_11.setText(_translate("Form", "挂车吨位："))
        self.btn_clear.setText(_translate("Form", "清除界面"))

